[package]
name = "RVuln"
version = "0.1.0"
authors = ["iinc0gnit0 <iinc0gnit0@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "0.9.3"